version: '3.7'


services:
  postgres:
    image: postgres:16.0 
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=superpass
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 30s
      timeout: 10s
      retries: 5

  vendor-order-service: 
    container_name: vendor-order-service
    build: ./backend
    image: vendor-order-service:version1
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - PORT=3000
      - DATABASE_URL=postgresql://vo_admin:adminpass@postgres:5432/vendor_orders
      - FRONT_END_URL=http://localhost:8000
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    depends_on:
      - vendor-order-service
    environment:
    - NODE_ENV=production
    - PORT=8000
    - VITE_API_ENDPOINT=http://localhost:3000/api/v1
    ports:
      - "8000:8000"

volumes:
  postgres_data:

